name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: extract release notes
        run: |
          sed "/^## \[${GITHUB_REF#refs/tags/}/, /^## \[/!d" CHANGELOG.md | \
            tail -n +2 | head -n -2 > /tmp/rn.md
          cat /tmp/rn.md
      - uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --release-notes /tmp/rn.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
